# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Zeebe Chaos Days
email: christopher.zell@camunda.com
description: >- # this means to ignore newlines until "baseurl:"
    "We will spent a day in a week to explore our system, documenting failure cases, building a hypothesis backlog and running chaos experiments, such that we can build more confidence in our system. For each chaos day we will create a blog entry. The entry will contain: what we have done and results of the chaos experiments. With that we can share the knowledge, whether we found a weakness or the confidence that we were able to withstand a failure scenario."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ChristopherZell
github_username:  zelldon

# Build settings
theme: plainwhite
plugins:
  - jekyll-feed

plainwhite:
  name: Zeebe Chaos Days
  tagline: Chaos Engineering meets Zeebe
  date_format: "%b %-d, %Y"
  portfolio_image: "assets/zeebe-logo.png"
  social_links:
    twitter: zeebeHQ
    github: zeebe-io

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
