apiVersion: v1
clusters:
- cluster:
    server: https://127.0.0.1:46807
  name: kind-kind
contexts:
- context:
    cluster: kind-kind
    namespace: kind-default
    user: kind-kind
  name: kind-kind
current-context: kind-kind
kind: Config
preferences: {}
