name: Release zbchaos Docker Image
on:
  pull_request: {} 
  release:
    types: [published]

jobs:
  publish-image:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.release.name || github.sha }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup BuildKit
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.DOCKER_GCR }}
      - name: Publish Docker Image
        uses: docker/build-push-action@v3
        with:
          context: go-chaos
          push: true
          tags: gcr.io/zeebe-io/zbchaos:${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
