name: Release Chaos Workers

on:
  release:
    types: [published]

jobs:
  publish-image:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.release.name }}
    steps:
          - run: |
              echo "Name: ${{ env.VERSION }}"
          - uses: actions/checkout@v2
          - name: Set up JDK 17
            uses: actions/setup-java@v2.4.0
            with:
              java-version: '17'
              distribution: 'temurin'
          - name: Package with Maven
            run: mvn -B package -DskipTests -f chaos-workers/chaos-worker/pom.xml             
          - name: Build docker image   
            id: build-image
            working-directory: chaos-workers/
            env:
                DOCKER_BUILDKIT: 1
                REGISTRY: gcr.io
                REPOSITORY: zeebe-io/zeebe-chaos-worker
                IMAGE_TAG: ${{ env.VERSION }}
            run: |                
                echo '${{ secrets.DOCKER_GCR }}' | docker login -u _json_key --password-stdin https://gcr.io
                docker build . -t "$REGISTRY/$REPOSITORY:latest" -t "$REGISTRY/$REPOSITORY:$IMAGE_TAG" --build-arg TOKEN="${{ secrets.SA_SECRET }}"
                docker push "$REGISTRY/$REPOSITORY:latest" 
                docker push "$REGISTRY/$REPOSITORY:$IMAGE_TAG"
