name: Release Chaos Workers

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
        version:
          description: 'The version to be released'
          required: true
          default: '0.1.0'

jobs:
  after-release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
    steps:
          - run: |
              echo "Name: ${{ env.VERSION }}"
          - uses: actions/checkout@v2
          - name: Set up JDK 11
            uses: actions/setup-java@v2.4.0
            with:
              java-version: '11'
              distribution: 'adopt'
          - name: Package with Maven
            run: mvn -B package -DskipTests -f chaos-workers/chaos-worker/pom.xml             
          - name: Build docker image   
            id: build-image
            working-directory: chaos-workers/
            env:
                DOCKER_BUILDKIT: 1
                REGISTRY: gcr.io
                REPOSITORY: zeebe-io/zeebe-chaos-worker
                IMAGE_TAG: ${{ env.VERSION }}
            run: |                
                echo '${{ secrets.DOCKER_GCR }}' | docker login -u _json_key --password-stdin https://gcr.io
                docker build . -t "$REGISTRY/$REPOSITORY:latest" -t "$REGISTRY/$REPOSITORY:$IMAGE_TAG" --build-arg TOKEN="${{ secrets.SA_TOKEN }}"
                docker push "$REGISTRY/$REPOSITORY:latest" 
                docker push "$REGISTRY/$REPOSITORY:$IMAGE_TAG"
