name: Release Chaos Workers

on:
  release:
    types: [published]
  workflow_dispatch: { }

jobs:
  after-release:
    runs-on: ubuntu-latest
    steps:
          - run: |
              echo "Name: ${{ github.event.release.name }} Description: ${{ github.event.release.body }}"
          - uses: actions/checkout@v2
          - name: Set up JDK 11
            uses: actions/setup-java@v2.4.0
            with:
              java-version: '11'
              distribution: 'adopt'
          #- name: Set release version
           # working-directory: chaos-workers/chaos-worker/
            #run: mvn versions:set "-DnewVersion=${{ github.event.release.name }}" -DgenerateBackupPoms=false
          #- name: Commit version 
            #run: |
              #git config user.name github-actions
              #git config user.email github-actions@github.com
              #git add .
              #git commit -m "Set release version to ${{ github.event.release.name }}"
              #git push
          - name: Package with Maven
            run: mvn -B package -DskipTests -f chaos-workers/chaos-worker/pom.xml             
          - name: Build docker image   
            id: build-image
            working-directory: chaos-workers/
            env:
                DOCKER_BUILDKIT: 1
                REGISTRY: gcr.io
                REPOSITORY: zeebe-io/zeebe-chaos-worker
                IMAGE_TAG: ${{ github.event.release.name }}
            run: |
                docker build . -t $REGISTRY/$REPOSITORY:latest -t $REGISTRY/$REPOSITORY:$IMAGE_TAG --build-arg TOKEN=${{ secrets.SA_TOKEN }}
                docker push $REGISTRY/$REPOSITORY:latest 
                docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
