name: Release zbchaos
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release and tag name'     
        required: true
        default: 'zbchaos-v1.X.0'

env:
  GO_VERSION: 1.19

jobs:
 go-release:
    name: Zbchaos go release
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go-chaos
    env:
      GITHUB_TOKEN: ${{ secrets.GHA_RELEASE }}
      RELEASE_VERSION: ${{ github.event.inputs.release }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "${{ env.GO_VERSION }}"
    - name: Setup BuildKit
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.DOCKER_GCR }}
    - name: "Run release script"
      # We defined everything as a script such that we can also run it manually/locally
      # Release contains building the artifacts, creating GitHub release, and publishing docker image
      run: ./release.sh
