name: 'Build and Test Chaos worker with Maven'

on:
  push: {}
  pull_request: {}
  workflow_dispatch: { }

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: docker pull camunda/zeebe:1.0.0
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2.4.0
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: |
       cd chaos-workers/chaos-worker/
       mvn -B verify
