name: 'Build and Test Chaos worker with Maven'

on:
  push: {}
  pull_request: {}
  workflow_dispatch: { }

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: docker pull camunda/zeebe:1.0.0
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2.4.0
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B verify