apiVersion: apps/v1
kind: Deployment
metadata:
  name: zbchaos-worker
  labels:
    app: zbchaos-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zbchaos-worker
  template:
    metadata:
      name: zbchaos-worker
      labels:
        app: zbchaos-worker
    spec:
      containers:
        - image: gcr.io/zeebe-io/zbchaos:1.4.4
          name: zbchaos-worker
          resources:
            limits:
              cpu: 4
              memory: 1Gi
            requests:
              cpu: 2
              memory: 500Mi
          volumeMounts:
            - mountPath: /.kube
              name: kubeconfig
          env:
            # We use here different names for the environment variables on purpose.
            # If we use the normal ZEEBE_ environment variables we would run
            # into conflicts when using multiple zeebe clients, the env vars will always overwrite
            # direct values
            - name: CHAOS_AUTOMATION_CLUSTER_AUTHORIZATION_SERVER_URL
              value: "https://login.cloud.camunda.io/oauth/token"
            - name: CHAOS_AUTOMATION_CLUSTER_CLIENT_ID
              value: "Jg9caDRuAWHchvM7JiaVlndL-qVFfp~0"
            - name: CHAOS_AUTOMATION_CLUSTER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: testbench-secrets
                  key: clientSecret
            - name: CHAOS_AUTOMATION_CLUSTER_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: testbench-secrets
                  key: contactPoint
          envFrom:
            - secretRef:
                name: zeebe-backup-store-s3
      volumes:
        - name: kubeconfig
          secret:
            defaultMode: 420
            items:
              - key: kubeconfig
                path: config
            secretName: zbchaos-worker-kubeconfig
